#TODO header

# Discord bot configurations
bot:
  # Whenever to enable the discord bot
  #
  # Allowed values: true, false
  enabled: false
  # The discord bot token, will b used only if the bot is enabled
  token: "Insert-token-here"
#TODO comment
data:
  activity:
   file: "times.yml"
   autosave:
     #seconds
     enabled: true
     interval: 600
     # First interval
     delay: 120
